
  version: 2.1
  jobs:
    build:
      docker:
        - image: cimg/node:current
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: npm install
    test:
      docker:
        - image: cimg/node:current
      steps:
        - checkout
        - run:
            name: Run tests
            command: npm test
  workflows:
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build              