version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Specify the Node.js version
    steps:
      - checkout  # Pull the latest code from GitHub
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
