version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.0.0

jobs:
  test:
    docker:
      - image: circleci/node:22  # Node version compatible with your project
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests
          command: npm test

  build-and-push:
    docker:
      - image: circleci/docker:latest
    steps:
      - setup_remote_docker:
          version: 20.10.7  # Specify the Docker version
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t keithblim/node-app-for-devops:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push keithblim/node-app-for-devops:latest

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: main
