version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:22
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build the Application
          command: npm run build

  test:
    docker:
      - image: circleci/node:22
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests
          command: npm test

  publish:
    docker:
      - image: circleci/docker:latest
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t keithblim/node-app-for-devops:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push keithblim/node-app-for-devops:latest

  deploy:
    docker:
      - image: circleci/docker:latest
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application..."

workflows:
  version: 2
  ci-and-cd:
    jobs:
      - build:
          name: build-main
          filters:
            branches:
              only: main
      - test:
          name: test-main
          filters:
            branches:
              only: main
      - build:
          name: build-release
          filters:
            branches:
              only: release
      - test:
          name: test-release
          filters:
            branches:
              only: release
      - publish:
          requires:
            - build-release
            - test-release
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - publish
          filters:
            branches:
              only: release
